apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
  namespace: cert-manager
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "15m"
  target:
    name: cloudflare-dns
  data:
  - secretKey: api-key
    remoteRef:
      key: secret/cloudflare/apitoken
      property: globalKey