apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns
  annotations:
    avp.kubernetes.io/path: "secret/data/cloudflare/apitoken"
  namespace: cert-manager
type: Opaque
data:
  api-key: <aigis.io_qunux.com>